# Generated by Django 4.2.3 on 2025-05-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_image_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_draft',
        ),
    ]
