# Generated by Django 4.2.3 on 2025-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
