# Generated by Django 4.2.3 on 2025-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_draft',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('published', 'Published')], default='published', max_length=10),
        ),
    ]
