# Generated by Django 4.2.3 on 2025-06-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, help_text='Upload an optional recipe video (MP4 only)', null=True, upload_to='recipe_videos/'),
        ),
    ]
